version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9000:9000"    # HDFS
      - "9870:9870"    # Web UI
    environment:
      - CLUSTER_NAME=test
    volumes:
      - ./hadoop/namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    ports:
      - "9864:9864"    # DataNode Web UI
    environment:
      - SERVICE_PRECONDITION="namenode:9000"
    volumes:
      - ./hadoop/datanode1:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    ports:
      - "9865:9864"    # DataNode Web UI
    environment:
      - SERVICE_PRECONDITION="namenode:9000"
    volumes:
      - ./hadoop/datanode2:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    ports:
      - "9866:9864"    # DataNode Web UI
    environment:
      - SERVICE_PRECONDITION="namenode:9000"
    volumes:
      - ./hadoop/datanode3:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

networks:
  hadoop:
    driver: bridge 